# Generated by Django 5.2.3 on 2025-09-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_add_resource_close_fields'),
    ]

    operations = [
        # Add indexes for Booking model - most critical for performance
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_booking_resource_start_status_idx ON booking_booking (resource_id, start_time, status);",
            reverse_sql="DROP INDEX IF EXISTS booking_booking_resource_start_status_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_booking_user_status_start_idx ON booking_booking (user_id, status, start_time);",
            reverse_sql="DROP INDEX IF EXISTS booking_booking_user_status_start_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_booking_status_start_idx ON booking_booking (status, start_time);",
            reverse_sql="DROP INDEX IF EXISTS booking_booking_status_start_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_booking_checkin_checkout_idx ON booking_booking (checked_in_at, checked_out_at);",
            reverse_sql="DROP INDEX IF EXISTS booking_booking_checkin_checkout_idx;"
        ),
        
        # Add indexes for Resource model
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_resource_active_closed_idx ON booking_resource (is_active, is_closed);",
            reverse_sql="DROP INDEX IF EXISTS booking_resource_active_closed_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_resource_type_active_idx ON booking_resource (resource_type, is_active);",
            reverse_sql="DROP INDEX IF EXISTS booking_resource_type_active_idx;"
        ),
        
        # Add indexes for UserProfile model
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_userprofile_role_inducted_idx ON booking_userprofile (role, is_inducted);",
            reverse_sql="DROP INDEX IF EXISTS booking_userprofile_role_inducted_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_userprofile_group_role_idx ON booking_userprofile (\"group\", role);",
            reverse_sql="DROP INDEX IF EXISTS booking_userprofile_group_role_idx;"
        ),
        
        # Add indexes for BookingTemplate model
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_bookingtemplate_public_user_idx ON booking_bookingtemplate (is_public, user_id);",
            reverse_sql="DROP INDEX IF EXISTS booking_bookingtemplate_public_user_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS booking_bookingtemplate_use_count_idx ON booking_bookingtemplate (use_count DESC);",
            reverse_sql="DROP INDEX IF EXISTS booking_bookingtemplate_use_count_idx;"
        ),
    ]
