# Generated by Django 4.2.23 on 2025-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarsyncpreferences",
            name="conflict_resolution",
            field=models.CharField(
                choices=[
                    ("aperture_wins", "Labitory wins"),
                    ("google_wins", "Google Calendar wins"),
                    ("ask_user", "Ask user each time"),
                    ("skip", "Skip conflicting events"),
                ],
                default="skip",
                help_text="How to handle conflicts between Labitory and Google Calendar",
                max_length=20,
            ),
        ),
    ]
