# Generated by Django 4.2.23 on 2025-09-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0014_add_billing_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Enable this configuration as the active SMS settings",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable SMS notifications globally"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this SMS configuration",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this configuration",
                    ),
                ),
                (
                    "twilio_account_sid",
                    models.CharField(help_text="Twilio Account SID", max_length=255),
                ),
                (
                    "twilio_auth_token",
                    models.CharField(
                        help_text="Twilio Auth Token (stored encrypted)", max_length=255
                    ),
                ),
                (
                    "twilio_phone_number",
                    models.CharField(
                        help_text="Twilio phone number in international format (e.g., +1234567890)",
                        max_length=20,
                    ),
                ),
                (
                    "message_character_limit",
                    models.PositiveIntegerField(
                        default=1600, help_text="Maximum characters per SMS message"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of retry attempts for failed messages",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this configuration has been successfully tested",
                    ),
                ),
                (
                    "last_test_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this configuration was tested",
                        null=True,
                    ),
                ),
                (
                    "last_test_result",
                    models.TextField(
                        blank=True, help_text="Result of the last configuration test"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_sms_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Configuration",
                "verbose_name_plural": "SMS Configurations",
                "db_table": "booking_smsconfiguration",
                "ordering": ["-is_active", "-updated_at"],
            },
        ),
    ]
