# Generated by Django 4.2.23 on 2025-09-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0015_add_sms_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="sms_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
