# Generated by Django 4.2.23 on 2025-09-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0016_add_async_notification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_locked",
            field=models.BooleanField(
                default=False,
                help_text="Whether the account is currently locked due to security issues",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of consecutive failed login attempts"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_failed_login",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last failed login attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lock_reason",
            field=models.CharField(
                blank=True, help_text="Reason for account lockout", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, help_text="When the account lockout expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the password was last changed", null=True
            ),
        ),
    ]
