# Generated by Django 4.2.23 on 2025-09-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0017_userprofile_account_locked_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorAuthentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("secret_key", models.CharField(blank=True, max_length=32)),
                ("backup_codes", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_email", models.EmailField(blank=True, max_length=254)),
                ("recovery_phone", models.CharField(blank=True, max_length=20)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("last_failed_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor_auth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Two-Factor Authentication",
                "verbose_name_plural": "Two-Factor Authentications",
                "db_table": "booking_twofactorauthentication",
            },
        ),
        migrations.CreateModel(
            name="TwoFactorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_twofactorsession",
                "indexes": [
                    models.Index(
                        fields=["user", "session_key"],
                        name="booking_two_user_id_6d57f2_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="booking_two_expires_c4f97f_idx"
                    ),
                ],
            },
        ),
    ]
