# Generated by Django 4.2.23 on 2025-09-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_add_comprehensive_database_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accessrequest",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image to display alongside the content - Max 5MB, JPEG/PNG/WEBP formats",
                null=True,
                upload_to="about_page/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("archived", "Archived"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancedocument",
            name="file",
            field=models.FileField(
                help_text="Maintenance documentation - Max 10MB, PDF/DOC/XLS formats",
                upload_to="maintenance_docs/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Resource image - Max 5MB, JPEG/PNG/WEBP formats",
                null=True,
                upload_to="resources/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="resourceissue",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the issue (optional) - Max 5MB, JPEG/PNG/WEBP formats",
                null=True,
                upload_to="issue_reports/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="userriskassessment",
            name="assessment_file",
            field=models.FileField(
                blank=True,
                help_text="Supporting documents (Excel, PDF, Word, etc.) - Max 20MB",
                null=True,
                upload_to="risk_assessments/%Y/%m/",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("resource", "user"),
                name="unique_pending_access_request",
            ),
        ),
    ]
