# Generated by Django 4.2.23 on 2025-09-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_add_archived_status_and_reset_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Optional URL for additional information about the resource",
            ),
        ),
    ]
