# Generated by Django 4.2.23 on 2025-09-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0022_add_url_to_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture - Max 2MB, JPEG/PNG formats",
                null=True,
                upload_to="avatars/%Y/%m/",
            ),
        ),
    ]
