# Generated by Django 4.2.23 on 2025-09-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_userprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="training_request",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="required_training_level",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="training_level",
        ),
        migrations.DeleteModel(
            name="TrainingRequest",
        ),
    ]
