# Generated by Django 4.2.23 on 2025-09-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0024_remove_notification_training_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrule",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_rules",
                to="booking.resource",
            ),
        ),
    ]
